#### Building Docker Image ####
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'asia-south1-docker.pkg.dev/admin-project-359810/my-repo/myapp:$SHORT_SHA', '-t', 'asia-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/myapp:${_IMAGE_TAG}', '.' ]

#### Pushing Docker Image ####
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: /bin/sh
  args: 
  - -c
  - |
    docker push asia-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/myapp:$SHORT_SHA
    docker push asia-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/myapp:${_IMAGE_TAG}

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_NUMBER/secrets/github-access-token/versions/latest
    env: 'GIT_ACCESS_TOKEN'

# options:
#   logging: CLOUD_LOGGING_ONLY
